### ISSUE TITLE
Multiprocessing Random Number Weirdness

### ISSUE THREAD

**Issue by petercwill** [HaroldRKingsberg/MLMC#5]
I observed strange behavior when trying to use multiprocessing in the following function:
```
def euler_asset_walk(self, nsteps, npaths):

        # weirdness with random numbers generated in multiprocessing???
        pool = multiprocessing.Pool(4)
     
        x = pool.map(
            path.calculate,
            [
                [path.create_simple_path] + [[self.assets], self.risk_free, self.expirary_time, nsteps]
                for _ in xrange(npaths)
            ]
        )

```

calling euler_asset_walk in a loop, for instance, produced the same sets of paths.

**Comment by HaroldRKingsberg** [comment]
Taking a look

**Comment by HaroldRKingsberg** [comment]
The problem seems to be one of seeding -- numpy seems to default its seed values in such a fashion that all processes started at the same time use the same seed.

For randomness, this is obviously unacceptable. I've created the SimpleGaussianSampleCreator, which uses python's native random module and doesn't have this issue.
